application:
  environment: !env APP_ENV, dev
  debug: !env APP_DEBUG, true

localization:
  locale: "en"
  supported_locales:
    - "en"
    - "fr"
  locale_path: "locale"
  timezone: "America/Toronto"

render:
  engine: "latte"
  directory: "app/Views"
  cache: "cache/latte"
  mode: "always"

leaf:
  name: "Zephyrus"
  version: "Preview"
  description: "A cohesive PHP framework. Clear by design. Powerful by nature."
  github_url: "https://github.com/zephyrus-framework/core"
  content_path: "content"
  sections:
    getting-started: "Start here"
    fundamentals: "Fundamentals"
  output_path: "dist"
  base_url: ""
  author: "Ophelios"
  author_url: "https://ophelios.com"
  license: "MIT"
